export const STRINGS = {
  common: {
    submit: '제출',
    cancel: '취소',
    save: '저장',
    edit: '수정',
    delete: '삭제',
    search: '검색',
    filter: '필터',
    all: '전체',
    loading: '로딩 중...',
    error: '오류가 발생했습니다',
    noData: '데이터가 없습니다',
    status: '상태',
    date: '날짜',
    floor: '층',
    detail: '상세',
    back: '뒤로',
    confirm: '확인',
    close: '닫기',
    new: '새로 작성',
    total: '전체',
    myRequests: '내 요청',
  },
  status: {
    submitted: '접수됨',
    reviewing: '검토중',
    in_progress: '처리중',
    completed: '완료',
    rejected: '반려',
    acknowledged: '확인됨',
    resolved: '해결됨',
    reported: '신고됨',
    matched: '매칭됨',
    claimed: '수령 완료',
    closed: '종료',
    stored: '보관중',
    notified: '알림 발송',
    registered: '등록됨',
    disposed: '폐기됨',
    vendor_assigned: '외주 배정',
    in_repair: '수리중',
    scheduled: '일정 확정',
    normal: '일반',
    urgent: '긴급',
    in_use: '사용중',
    in_stock: '재고',
    under_repair: '수리중',
    hot: '덥다 🥵',
    cold: '춥다 🥶',
  },
  nav: {
    home: '홈',
    lostFound: '분실물',
    equipment: '전산장비',
    temperature: '온도 민원',
    complaint: '불편사항',
    parcel: '택배',
    facility: '시설 수리',
    notifications: '알림',
    admin: '관리자',
    adminDashboard: '운영 현황',
    logout: '로그아웃',
  },
  modules: {
    complaint: {
      title: '불편사항 건의',
      newTitle: '불편사항 등록',
      categories: {
        facility: '시설',
        living_environment: '생활환경',
        welfare: '복지',
        it: 'IT',
        other: '기타',
      },
    },
    equipment: {
      title: '전산장비',
      newTitle: '전산장비 요청',
      types: {
        inspection: '점검 요청',
        replacement: '교체 요청',
        purchase: '구매 요청',
        software_purchase: 'SW 구입 문의',
        network_inspection: '네트워크 점검',
      },
    },
    lostFound: {
      lostTitle: '분실물 신고',
      foundTitle: '습득물 신고',
      newLost: '분실 신고',
      newFound: '습득물 등록',
      categories: {
        electronics: '전자기기',
        clothing: '의류/잡화',
        wallet_card: '지갑/카드',
        other: '기타',
      },
    },
    parcel: {
      title: '택배 관리',
      newTitle: '택배 등록',
      carriers: [
        'CJ대한통운',
        '롯데택배',
        'GS포스트박스',
        '우체국',
        '한진택배',
        '쿠팡로켓',
        '기타',
      ],
    },
    facility: {
      title: '시설 수리 요청',
      newTitle: '시설 수리 요청',
      categories: {
        lighting: '조명',
        furniture: '가구',
        door: '문/도어',
        plumbing: '배관',
        electrical: '전기',
        cleaning: '청소',
        other: '기타',
      },
    },
    temperature: {
      title: '온도 민원',
      newTitle: '온도 민원 접수',
      feelings: {
        hot: '덥다 🥵',
        cold: '춥다 🥶',
      },
    },
  },
} as const
